### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by HackerYijia**

### CODE REVIEW

**Comment by NuraadGit** [comment]
might not pull, idk maybe it will, reason why i think we shouldnt pull is cus u removed the message to mojang employees

**Comment by NuraadGit** [comment]
wayyyy too many

**Comment by OtterCodes102** [comment]
agreed

**Comment by HackerYijia** [comment]
@NuraadGit I have the same message to mojiang employees. I just changed it so it says I removed.

**Comment by HackerYijia** [comment]
Emojis makes it looks modern?

**Comment by NuraadGit** [comment]
Sure emojis make it look modern but that’s too many you put

**Comment by vukle** [comment]
closed due to inactivity

**Comment by NuraadGit** [comment]
trolled 2

**Pull request closed without merging**
