### PR TITLE
Optimized the run_chmod.sh and added a utility pull_mcp918.sh

### PR DESCRIPTION
**Pull request by Hellscaped**
Ignore the empty file things, git recognized me running chmod and thought it was a change it thought it should commit.

### CODE REVIEW

**Comment by ShoelessTom** [comment]
denied

**Comment by Hellscaped** [comment]
> denied

nuh uh you dont have write access

**Comment by vukle** [comment]
optimize chmod has no use, other than just making the code shorter, along with gitignore is completely useless since no program creates those directories, mcp puller script is likely to get our repo taken down and im currently removing it from buildtools. please do better next time.

**Comment by NuraadGit** [comment]
m

**Pull request closed without merging**
