### PR TITLE
added YoinkAssets.bat and YoinkAssets.sh

### PR DESCRIPTION
**Pull request by radmanplays**

### CODE REVIEW

**Comment by vukle** [comment]
I don't feel comfortable accepting this change since the repo could get deleted over this. @NuraadGit Opinions?

**Comment by radmanplays** [comment]
> I don't feel comfortable accepting this change since the repo could get deleted over this. @NuraadGit Opinions?

it wouldn't bc its downloading the files from mojang's own servers. mojang cant dmca a repo that dosnt have the files. EaglerReborn (a fork of eaglercraft) has the YoinkAssets.bat and YoinkAssets.sh and didnt get dmca'd

**Comment by vukle** [comment]
Understood, but I still don't feel comfortable.

**Comment by NuraadGit** [comment]
Not adding this due to a chance of getting dmca

**Comment by literally1984** [comment]
I mean, I feel like radman is right. No copyrighted material is actually going to be hosted on this repository per this change.

**Comment by NuraadGit** [comment]
it still grabs some copyrighted material, we want you to own the game without getting the assets illegally

**Comment by OtterCodes102** [comment]
> want

it has links to the files in the compile gui

**Comment by MythicalTrashcan** [comment]
> > I don't feel comfortable accepting this change since the repo could get deleted over this. @NuraadGit Opinions?
> 
> it wouldn't bc its downloading the files from mojang's own servers. mojang cant dmca a repo that dosnt have the files. EaglerReborn (a fork of eaglercraft) has the YoinkAssets.bat and YoinkAssets.sh and didnt get dmca'd

It got DMCA'd now for whatever reason. Probably not related.

**Comment by vukle** [comment]
very ironic

**Comment by grandpa1946** [comment]
> I mean, I feel like radman is right. No copyrighted material is actually going to be hosted on this repository per this change.

me not getting credits for yoinkassets.bat ._.

**Pull request closed without merging**
